### ISSUE TITLE
setting up with docker-compose-letsencrypt-nginx-proxy-companion

### ISSUE THREAD

**Issue by howong** [steevepay/gitlab-docker-letsencrypt#4]
To ensure I'm troubleshooting correctly, my assumption on how this works:

**docker-compose-letsencrypt-nginx-proxy-companion** serves as a proxy and **gitlab-docker-letsencrypt** should sit behind the proxy as one of the websites?

**Comment by steevepay** [comment]
Hello, sorry for the delay. You are right, you can setup other websites behind the proxy beside `gitlab-docker-letsencrypt`. All you need is to defined a Dockerfile with the environment variables required for `docker-compose-letsencrypt-nginx-proxy-companion`.

**Comment by steevepay** [comment]
Hello, did you succeed to make it work?

**Comment by howong** [comment]
Hi! I appreciate your follow up. Since we have a small team, it was sufficient to run the gitlab-ee docker image standalone without a proxy. I was able to get SSL and single sign on working following the directions on Gitlab's wiki.
