### ISSUE TITLE
 Server responded with 0 code

### ISSUE THREAD

**Issue by cod3r0k** [steevepay/gitlab-docker-letsencrypt#6]
When I want to upload image in wiki, it doesn't be uploaded and gets an error. Can you help me? @b41somp  @steevepay

**Comment by steevepay** [comment]
- Check the owner and group for the GitLab files/directories.
- Check your Nginx webproxy upload limit option

**Comment by cod3r0k** [comment]
> * Check the owner and group for the GitLab files/directories.
> * Check your Nginx webproxy upload limit option

Thanks but I'm just go through your steps and the Git is OK but I can't upload image (I increase the upload limit and it is not resolved).

How can I check owner and group? it is in the docker . isn't it?

**Comment by steevepay** [comment]
Check the owner/group of the following path on your server:
- ${GITLAB_DATA_PATH}data
- ${GITLAB_DATA_PATH}logs
- ${GITLAB_DATA_PATH}config

**Comment by steevepay** [comment]
Any news?
